Repository Parabeac/Parabeac-Core, pull requests merged in 2020-10, with the labels that each got.

#76 Update README.md
  README.md
Labels: HacktoberFest, documentation

#75 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: HacktoberFest, documentation

#87 (fix:#51) Refactored PBParam to PBVariable
  lib/generation/generators/pb_flutter_generator.dart
  lib/generation/generators/pb_variable.dart
  lib/generation/generators/pb_widget_manager.dart
  lib/generation/generators/symbols/pb_sym_mas_param_gen.dart
  pubspec.yaml
Labels: refactor

#104 Fixed Json serialization, conflicts and interpretation errors.
  lib/controllers/interpret.dart
  lib/interpret_and_optimize/entities/inherited_scaffold.g.dart
  lib/interpret_and_optimize/entities/layouts/column.dart
  lib/interpret_and_optimize/entities/layouts/row.dart
  lib/interpret_and_optimize/entities/layouts/row.g.dart
  lib/interpret_and_optimize/entities/layouts/stack.dart
  lib/interpret_and_optimize/entities/layouts/stack.g.dart
  lib/interpret_and_optimize/services/pb_layout_generation_service.dart
  pubspec.yaml
Labels: hotfix

#85 Using Dart's ArgParser to parse arguments
  lib/main.dart
  parabeac.dart
Labels: HacktoberFest, enhancement, refactor

#120 Fixed Figma crashing when no output path is given. Removed unnecessar…
  lib/APICaller/api_call_service.dart
  lib/input/figma/helper/image_helper.dart
  lib/main.dart
Labels: hotfix
